### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by diskria** [PlanetTeamSpeakk/DevLogin#10]
Looks like it came out on 1.20

```
[11:07:38] [main/ERROR] (DevLogin) Could not login using Microsoft account.
 java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at fabric.com.ptsmods.devlogin.MSA.lambda$reqProfile$14(MSA.java:318) ~[devlogin-3.2.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.doRequest(MSA.java:385) ~[devlogin-3.2.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.reqProfile(MSA.java:312) ~[devlogin-3.2.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.login(MSA.java:91) ~[devlogin-3.2.2.jar:?]
	at fabric.com.ptsmods.devlogin.DevLogin.loginMSA(DevLogin.java:173) ~[devlogin-3.2.2.jar:?]
	at fabric.com.ptsmods.devlogin.DevLogin.modifyArgs(DevLogin.java:57) ~[devlogin-3.2.2.jar:?]
	at net.minecraft.client.main.Main.localvar$zjf000$devlogin$modifyArgs(Main.java:521) ~[minecraft-merged-project-root-1.20-net.fabricmc.yarn.1_20.1.20+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:106) ~[minecraft-merged-project-root-1.20-net.fabricmc.yarn.1_20.1.20+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by PlanetTeamSpeakk** [comment]
I've had this issue on 1.19.2 as well since two days ago (I believe). Pretty sure Microsoft changed their API or just doesn't like me anymore. Will have to look into this.

**Comment by RedLime** [comment]
same issue on 1.16.1, and re-login does works I think it is related about refresh token

**Comment by PlanetTeamSpeakk** [comment]
It seems like the procedure acquires tokens just fine, but the final endpoint, the one that acquires the profile, is saying the token is invalid and returns a 401 error. I have no idea what causes this and I cannot really try to make a new Azure application because Azure keeps kicking me out because of some stupid error with their system.

**Comment by PlanetTeamSpeakk** [comment]
Yeah, just confirmed by using the client id of another application that it is indeed because of my Azure app. Not a clue why and not a clue why they won't let me make a new one.

**Comment by PlanetTeamSpeakk** [comment]
I've created a new account and a new application which appears to work, except Minecraft has improved the security around authenticating with their APIs (more here: https://aka.ms/AppRegInfo) which requires me to fill in a form and be approved. I have no idea how long this approval takes, but until then, the mod will not function.

**Comment by PlanetTeamSpeakk** [comment]
Finally got an update on this issue. I've received an email from Mojang saying they're working on the submitted forms at the moment. No word yet as to when it'll get reviewed, but at least they're working on it.

**Comment by PlanetTeamSpeakk** [comment]
Issue has been resolved.
