### ISSUE TITLE
When using ViaFabricPlus it crashes

### ISSUE THREAD

**Issue by SinanAkkoyun** [PlanetTeamSpeakk/DevLogin#12]
Hey, when I install ViaFabricPlus (on 1.20.1 all latest verisons on fabric):

```
[20:41:55] [main/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: io/netty/handler/codec/DefaultHeaders$ValueValidator
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: io/netty/handler/codec/DefaultHeaders$ValueValidator
        at org.asynchttpclient.RequestBuilderBase.<init>(RequestBuilderBase.java:98) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.RequestBuilderBase.<init>(RequestBuilderBase.java:92) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.BoundRequestBuilder.<init>(BoundRequestBuilder.java:25) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.DefaultAsyncHttpClient.requestBuilder(DefaultAsyncHttpClient.java:312) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.DefaultAsyncHttpClient.prepare(DefaultAsyncHttpClient.java:151) ~[async-http-client-2.12.3.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.doRequest(MSA.java:370) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.reqProfile(MSA.java:312) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.login(MSA.java:91) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.DevLogin.loginMSA(DevLogin.java:173) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.DevLogin.modifyArgs(DevLogin.java:57) ~[devlogin-3.3.2.jar:?]
        at net.minecraft.client.main.Main.localvar$zdl000$devlogin$modifyArgs(Main.java:521) ~[minecraft-clientonly-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:100) ~[minecraft-clientonly-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.DefaultHeaders$ValueValidator
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at org.asynchttpclient.RequestBuilderBase.<init>(RequestBuilderBase.java:98) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.RequestBuilderBase.<init>(RequestBuilderBase.java:92) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.BoundRequestBuilder.<init>(BoundRequestBuilder.java:25) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.DefaultAsyncHttpClient.requestBuilder(DefaultAsyncHttpClient.java:312) ~[async-http-client-2.12.3.jar:?]
        at org.asynchttpclient.DefaultAsyncHttpClient.prepare(DefaultAsyncHttpClient.java:151) ~[async-http-client-2.12.3.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.doRequest(MSA.java:370) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.reqProfile(MSA.java:312) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.MSA.login(MSA.java:91) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.DevLogin.loginMSA(DevLogin.java:173) ~[devlogin-3.3.2.jar:?]
        at fabric.com.ptsmods.devlogin.DevLogin.modifyArgs(DevLogin.java:57) ~[devlogin-3.3.2.jar:?]
        at net.minecraft.client.main.Main.localvar$zdl000$devlogin$modifyArgs(Main.java:521) ~[minecraft-clientonly-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:100) ~[minecraft-clientonly-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
```

I would really like to develop with the ViaFabricPlus running alongside, how is this fixable?

**Comment by PlanetTeamSpeakk** [comment]
Think ViaFabric Plus comes with its own version of Netty or whatever. I'll see if I can switch to Apache's HTTP client, pretty sure that one's standalone.

**Comment by SinanAkkoyun** [comment]
Ah I see, thank you :) In the meantime, I switched to IngameAccountSwitcher, so you do not need to do the work for me, only if you think that others would be in the same situation (I have not seen anyone having this issue before)
