### ISSUE TITLE
Crash on login (V3.3.2)

### ISSUE THREAD

**Issue by CaramelFur** [PlanetTeamSpeakk/DevLogin#13]
Heya, I'm trying to get devlogin to work for Minecraft 1.20.2, but it doesn't seem to work anymore.
It gives this error:
```
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'java.util.UUID com.mojang.util.UUIDTypeAdapter.fromString(java.lang.String)'
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.UUID com.mojang.util.UUIDTypeAdapter.fromString(java.lang.String)'
	at fabric.com.ptsmods.devlogin.MSA.lambda$reqProfile$14(MSA.java:319) ~[devlogin-3.3.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.doRequest(MSA.java:385) ~[devlogin-3.3.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.reqProfile(MSA.java:312) ~[devlogin-3.3.2.jar:?]
	at fabric.com.ptsmods.devlogin.MSA.login(MSA.java:124) ~[devlogin-3.3.2.jar:?]
	at fabric.com.ptsmods.devlogin.DevLogin.loginMSA(DevLogin.java:173) ~[devlogin-3.3.2.jar:?]
	at fabric.com.ptsmods.devlogin.DevLogin.modifyArgs(DevLogin.java:57) ~[devlogin-3.3.2.jar:?]
	at net.minecraft.client.main.Main.localvar$zzf000$devlogin$modifyArgs(Main.java:521) ~[minecraft-merged-project-root-1.20.2-net.fabricmc.yarn.1_20_2.1.20.2+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:109) ~[minecraft-merged-project-root-1.20.2-net.fabricmc.yarn.1_20_2.1.20.2+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 3 more
```

These are my fabric version:
```
	minecraft_version=1.20.2
	yarn_mappings=1.20.2+build.1
	loader_version=0.14.22
	loom_version=1.3-SNAPSHOT
	fabric_language_kotlin_version = 1.10.10+kotlin.1.9.10
```

Hopefully this is enough info to be able to fix the bug. If more is required ask away. Thank you.

**Comment by PlanetTeamSpeakk** [comment]
Ah, I suppose they either changed or removed that class. Will look into this.

**Comment by CaramelFur** [comment]
Hi, I've fixed the bug for ya, so feel free merge #14 and push a new release

**Comment by CaramelFur** [comment]
Heya @PlanetTeamSpeakk have you been able to push a new release yet? No rush, just making sure ya aint forgot. 😅

**Comment by PlanetTeamSpeakk** [comment]
I did, my bad. Publishing rn.

**Comment by PlanetTeamSpeakk** [comment]
It's published. You should be able to use it in about half an hour.

**Comment by CaramelFur** [comment]
Ah no worries, it happens, thank you so much.
