### ISSUE TITLE
Devlogin 3.5 causes architectury loom interface inject crash on forge and neoforge.

### ISSUE THREAD

**Issue by qyl27** [PlanetTeamSpeakk/DevLogin#17]
## Code:  
SinoCraftProject/SinoSeries [56891ab](https://github.com/SinoCraftProject/SinoSeries/tree/56981ab73bf74017b1b9664796f705bc37c7a6ae).

## Step to reproduce:  
1. Clone this commit.
2. Uncomment `sinoseries-meta/sinoseries-meta-forge/build.gradle#L46`.
3. IDEA sync project.
4. Run `Forge Client` in IDEA.

## Log:  
```text
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:96)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10)
	at net.minecraftforge.bootstrap@1.2.0/net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98)
	at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.1.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: games/moegirl/sinocraft/sinocore/injectables/ITabItemProperties
	at MC-BOOTSTRAP/fmlloader@1.20.2-48.1.0/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:30)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.client.main.Main.main(Main.java:165)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: games/moegirl/sinocraft/sinocore/injectables/ITabItemProperties
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:427)
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367)
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.world.item.Items.<clinit>(Items.java:1399)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.world.level.block.ComposterBlock.bootStrap(ComposterBlock.java:71)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:58)
	at TRANSFORMER/minecraft@1.20.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:165)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: games.moegirl.sinocraft.sinocore.injectables.ITabItemProperties
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:392)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:392)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more

```

**Comment by PlanetTeamSpeakk** [comment]
I can reproduce this issue with version 3.5, but not with 3.5.1. However, with 3.5.1, I get a different error. Namely one where Forge complains it cannot find `META-INF/versions`.

After some digging, it turns out this different error is actually caused by a bug in loom. This bug happens when mods are remapped. Using modImplementation remaps a mod and all of its dependencies, even the dependencies that aren't mods themselves. This remapping strips multi-release metadata while keeping the multi-release flag, resulting in JARs with broken metadata. Forge expects this metadata to exist when the multi-release flag is true while scanning the JAR, but because it was stripped, it errors.

The solution is to upgrade to 3.5.1 and remove the transitive dependencies (i.e., async-http-client and the netty jars it includes). This is safe to do since this version because the mod will fallback to a different HTTP client.

You can achieve this by replacing the dependency with `modImplementation("com.ptsmods:devlogin:3.5.1:forge") { transitive false }`.
